version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
  redis:
    image: "redis:latest"
    # expose:
    #   - "6379"
    ports:
      - "6380:6379"  # Expose Redis port 6379 to host port 6379

