# Use the official Go image which includes necessary tools to build Go projects.
# Make sure to match the Go version with what you need for your project.
FROM golang:1.19-buster as builder

# Set the Current Working Directory inside the container
WORKDIR /app

# Copy go mod and sum files
COPY go.mod go.sum ./

# Download all dependencies. Dependencies will be cached if the go.mod and go.sum files are not changed
RUN go mod download

# Copy the source code into the container
COPY . .

# Build the Go app
RUN go build -o my-go-service ./cmd/server

RUN apt-get update && apt-get install -y \
    redis-tools \
    && rm -rf /var/lib/apt/lists/*

# Expose port 8080 to the outside world
EXPOSE 6380:6379

# Command to run the executable
CMD ["bash"]
